---
abstract: "Perl interface to Google's Weather API"
author:
  - unknown
build_requires:
  Test::More: 0
  Test::Pod: 0
  Test::Simple: 0
  Test::Warn: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Weather-Google
provides:
  Weather::Google:
    file: lib/Weather/Google.pm
    version: 0.06
requires:
  Carp: 0
  LWP::Simple: 0
  XML::Simple: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
